### ISSUE TITLE
npm ERR! exited with error code: 128

### ISSUE THREAD

**Issue by AlexVFornazieri** [oanhnn/html5project#1]
Hey Oanhnn,

I'm starting in the NPM world and i try use your boilerplate code 'professional-jquery-webpack-es6', but when running 'npm install' he not completing, you can help me with it? thanks for all help.

$ npm install
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alexvfornazieri/.npm/_logs/2017-06-03T00_15_33_550Z-debug.log

**Comment by oanhnn** [comment]
@AlexVFornazieri 
Can you show about:
- OS
- nodejs version
- npm version

**Comment by AlexVFornazieri** [comment]
@oanhnn 
Sorry for the long delay, took time away from the activities.

Recently had to format my PC because of other problems and when running the installation command again everything worked perfectly :)

Thank you for your attention.

OS: Ubuntu 16.04
Node -v 6.11.0
Npm --version 5.1.0
